// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CAPA.CONSUMO.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Empresa
    {
        /// <summary>
        /// Initializes a new instance of the Empresa class.
        /// </summary>
        public Empresa() { }

        /// <summary>
        /// Initializes a new instance of the Empresa class.
        /// </summary>
        public Empresa(int? empresaId = default(int?), string nombre = default(string), int? sedeId = default(int?), string sedeNombre = default(string))
        {
            EmpresaId = empresaId;
            Nombre = nombre;
            SedeId = sedeId;
            SedeNombre = sedeNombre;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EmpresaId")]
        public int? EmpresaId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Nombre")]
        public string Nombre { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SedeId")]
        public int? SedeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SedeNombre")]
        public string SedeNombre { get; set; }

    }
}
