// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CAPA.CONSUMO.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class EstadoSolicitud
    {
        /// <summary>
        /// Initializes a new instance of the EstadoSolicitud class.
        /// </summary>
        public EstadoSolicitud() { }

        /// <summary>
        /// Initializes a new instance of the EstadoSolicitud class.
        /// </summary>
        public EstadoSolicitud(bool? estaCorrecto = default(bool?), string mensajeRespuesta = default(string), int? tipoNotificacionId = default(int?))
        {
            EstaCorrecto = estaCorrecto;
            MensajeRespuesta = mensajeRespuesta;
            TipoNotificacionId = tipoNotificacionId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EstaCorrecto")]
        public bool? EstaCorrecto { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MensajeRespuesta")]
        public string MensajeRespuesta { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TipoNotificacionId")]
        public int? TipoNotificacionId { get; set; }

    }
}
