// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CAPA.CONSUMO.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Usuario
    {
        /// <summary>
        /// Initializes a new instance of the Usuario class.
        /// </summary>
        public Usuario() { }

        /// <summary>
        /// Initializes a new instance of the Usuario class.
        /// </summary>
        public Usuario(string apellidoMaterno = default(string), string apellidoPaterno = default(string), string nombreUsuario = default(string), string nombres = default(string), int? usuarioId = default(int?))
        {
            ApellidoMaterno = apellidoMaterno;
            ApellidoPaterno = apellidoPaterno;
            NombreUsuario = nombreUsuario;
            Nombres = nombres;
            UsuarioId = usuarioId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ApellidoMaterno")]
        public string ApellidoMaterno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ApellidoPaterno")]
        public string ApellidoPaterno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NombreUsuario")]
        public string NombreUsuario { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Nombres")]
        public string Nombres { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UsuarioId")]
        public int? UsuarioId { get; set; }

    }
}
